In [2]:
import numpy as np

In [23]:
#Lista con tutti 0
np.zeros(11, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#Tabella 4x5 con tutti 1 decimale. Vettore bidimensionale, matrice con due dimensioni (4=righe, 5=colonne)
np.ones((4, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# Create a 6x9 array filled with 6.19 (6 righe, 9 colonne)
np.full((6, 9), 6.19)

array([[6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19],
       [6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19],
       [6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19],
       [6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19],
       [6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19],
       [6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19, 6.19]])

In [26]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 32, stepping by 2
np.arange(0, 32, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [38]:
np.arange(12, 50, 3)

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [43]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
# Create an array of five values evenly spaced between 0 and 2
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
# Create a 4x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((4, 3))

array([[0.54409068, 0.1545792 , 0.62329481],
       [0.71651434, 0.03041994, 0.41262395],
       [0.14789634, 0.22480725, 0.90020628],
       [0.09195729, 0.6092998 , 0.87692423]])

In [29]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.00718831, -0.98993003, -1.70509672],
       [-0.03356511, -0.79742267,  0.64537163],
       [-0.36581092,  1.54121146, -3.08232641]])

In [30]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 2, 5],
       [7, 4, 2],
       [8, 2, 5]])

In [31]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<font color='red'>Guardare su numpy la specificità di ogni funzione utilizzata in questa lezione e inserire a cosa serve sul file di Numbers e guardare capitolo 2.1 e 2.2 </font>